layout_spectrum: 0.8996627
typography_spectrum: 0.2731872
color:
  lightness: 0.7487352
  brandStrength: 0.7596965
  saturation: 0.5733558
  rhythmicContrast: 0.2917369
  brandColors:
    - '#381742'
    - '#030103'
    - '#AD7799'
    - '#FFFCFF'
    - '#9A4C39'
name: The Norwegian Life Coach
